### ISSUE TITLE
Rollback occurrence in AGE Website

### ISSUE THREAD

**Issue by jbiz805** [apache/age-website#94]
@pdpotter 
@shinhanbyeol 

There seems to be a rollback issue on the AGE Website. 
All the spelling and grammar errors I've requested David(shinhanbyeol) to apply and the Github star/contributor tracking feature Andrew(aked21) requested disappeared from the website.

Upon checking with David, the rollback seemed to have occurred due to renewed AGE Documentation. 
Is there some sort of setting that does not affect the details on the website while renewing AGE documentation? 

It would be a hassle to recover or edit contents on the website every time the document is edited and applied.

**Comment by JoshInnis** [comment]
@pdpotter @shinhanbyeol There are multiple branches that are told to with 

```
publish:
  whoami: asf-site
```

in the .asf.yaml, could that be the issue

**Comment by pdpotter** [comment]
> @pdpotter @shinhanbyeol There are multiple branches that are told to with
> 
> ```
> publish:
>   whoami: asf-site
> ```
> 
> in the .asf.yaml, could that be the issue

That shouldn't be the issue. From https://cwiki.apache.org/confluence/display/INFRA/Git+-+.asf.yaml+features: `The configuration file is specific to the branch in which it resides and only code blocks with a whoami matching the branch name will run.` This does mean that the `whoami` section in the `.asf.yaml` file in the `new-site` branch doesn't really doe anything and can be removed I think.

**Comment by pdpotter** [comment]
@jbiz805 can you point me to the commits related to the changes that aren't applied on the website? I can't seem to find them. The typo fixed in https://github.com/apache/age-website/commit/287419281ec7b06988871cb8d64d9484624b8d5e seems to be correctly fixed on the website (at the bottom of https://age.apache.org/joinus).

**Comment by jbiz805** [comment]
@pdpotter oh, i actually requested to @shinhanbyeol separately via chat, not through github. That's why commits related to the changes aren't here.

**Comment by jbiz805** [comment]
@pdpotter seems to be fixed now.
@shinhanbyeol did you fix it?

**Comment by shinhanbyeol** [comment]
> @pdpotter seems to be fixed now. @shinhanbyeol did you fix it?

No, I couldn't fix it.
I just did the restoration of the website

If deployment occurs in the master branch, the same thing will happen again.

**Comment by jbiz805** [comment]
> > @pdpotter seems to be fixed now. @shinhanbyeol did you fix it?
> 
> No, I couldn't fix it. I just did the restoration of the website
> 
> If deployment occurs in the master branch, the same thing will happen again.

@pdpotter Are there ways to avoid this from happening every deployment?

**Comment by pdpotter** [comment]
I don't quite understand how a commit on the master branch, triggering the `Build documentation` action, affects changes on the website to be rolled back. The last two deploys after a commit on the master branch (https://github.com/apache/age-website/commit/39f4ad4f29864181987cea90048d423969a42ec6 and https://github.com/apache/age-website/commit/562fe1d9ecdf1957d42419a9a95a469c010a9943) only make changes to the `age-manual` directory in the `asf-site` branch. This `asf-site` branch contains the html files (and css an js) that are used for the website.

I did detect a rollbacks when changes in the `new-site` branch are made, as in the triggered `build gatsby` action, all files and directories in the `asf-site` branch are overridden. The `build gatsby` action does not build other versions of the documentation than `master` (e.g., `v0.6.0`). https://github.com/apache/age-website/pull/90 should solve this issue.

In the future, the `age-dev-manual` folder that would be created by the `Build documentation` action in the `developer-manual` branch would be overridden as well, so an additional build step should be added to the workflow to rebuild this documentation as well. @JoshInnis did you remove the action in the `developer-manual` branch (https://github.com/apache/age-website/commit/390e6d39c8672de7a67f41c4d6415c9c69bf5667) because it rolled back changes in the website?

It would be easier and faster if the `build gatsby` action triggered by the `new-site` branch wouldn't overwrite the `age-manual` and `age-dev-manual` folders, but I haven't found a way to do this.

**Comment by pdpotter** [comment]
> Why don't you add the process of building web-site resources to GitHub workflows on the master branch? https://github.com/apache/age-website/blob/new-web/.github/workflows/web-deploy.yml (see )
> 
> We don't know the cause of the problem at the moment, so I think we can solve the problem if we deal with it this way. If you agree with @pdpotter, can I modify the build-document.yml file?

I created a pull request that should do this: #98. Can you please review?


> The isuue of #90 is. See build-documentation.yml and run the same command as `spinx-multiversion docs build/html`. I am still having a hard time because the v0.6.0 version of the document has not been made.
> 
> https://github.com/apache/age-website/blob/new-web/.github/web-deploy.yml Could you check the link above and review the code?

The link you provided doesn't seem to exist (I get a 404).
The v0.6.0 version of the document is not made because the v0.6.0 branch is not fetched when running web-deploy.yml. PR #90 fixes this by fetching all branches before `spinx-multiversion docs build/html` is run (see https://github.com/apache/age-website/pull/90/commits/e96273449fabcb112a1eceaa2b2c69643e5d77f5).
